name: CI

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}-latest
    if: |
      !(contains(github.event.pull_request.title, '[ci skip]')
        || contains(github.event.head_commit.message, '[ci skip]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.7 ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, ragel
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 1
          apt-get: ragel
          brew: ragel
          mingw: _upgrade_ openssl ragel

      - name:  bundle install
        shell: pwsh
        run:   |
          bundle install --jobs 4 --retry 3 --path=.bundle/puma

      - name: compile
        run:  bundle exec rake compile

      - name: test
        timeout-minutes: 10
        run: bundle exec rake test:all
